"""Add tour_completed to User

Revision ID: 72f3c24fd7e8
Revises: 73c603b7d8a8
Create Date: 2026-07-12 11:09:04.862045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f3c24fd7e8'
down_revision: Union[str, Sequence[str], None] = '73c603b7d8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tour_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tour_completed')
    # ### end Alembic commands ###
